= GSRI server manager: usage guide

== Requirements

=== Softwares

* https://github.com/PowerShell/PowerShell[Pwsh 7+]: appliction runtime
* https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip[Steamcmd]: used for arma 3 server and workshop items download
* https://cli.github.com/[GitHub CLI]: used for Github repositories release content download

All 3 softwares should be accessible from the system PATH environment variable.

=== Accounts

* https://github.com/login[A github account]
* https://store.steampowered.com/login[A steam account] with the following caracteristics:
** Own https://store.steampowered.com/app/107410[Arma 3 base game] (DLC not needed)
** Not https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A[limited account] (buying Arma 3 should be enough)
** https://help.steampowered.com/en/faqs/view/06B0-26E6-2CF8-254C[Steam Guard on] is recommended

== Installation

=== Environment variables

STEAM_USERNAME:: Login to your steam account used to download binaries and workshop contents

=== Authentication

==== SteamCMD

This tool needs to log into the Steam network, because you need to own Arma 3 in order to download mods and dedicated server. The tool will use the environment variable `STEAM_USERNAME` and the steamcmd cached credentials. You need to authenticate once with the steamcmd tool before using the tool. You will need to authenticate again when your password change, or after adding or removing steam guard.

Use the following command to initialize credentials cache:

`steamcmd +login <username> <password> +quit`

If you have Steam Guard activated, you will need to enter a valid token.

==== Github CLI

NOTE: You may ignore this section if you don't intend to download missions or mods from GitHub

The same principles apply to the Github CLI. The GitHub CLI is used to download missions and mods from GitHub repositories. The CLI requires the client to authenticate despite the release contents to be publicly available. However, this allows you to access private repositories or enterprise servers as well.

Use the following command to initialize credentials cache:

`gh auth login --with-token < token.txt`

== Server configuration

All configuration regarding your server must go into a configuration file. This file is expected to use PSD1 format. You can use a custom path for the file using `-ConfigFilename`

Exemple file:

```psd1
@{
    Port             = 2302                                # main port used by the server
    ServerAffinity   = 5                                   # bitmask for CPU affinity of the server
    HeadlessAffinity = 10                                  # bitmask for CPU affinity of the headless client

    Hostname         = '[FR] SERVER NAME | www.gsri.team'  # name of the server visible on the launcher
    Password         = 'bouh!'                             # password for client connection
    Players          = 32                                  # max players for the server
    VerifySignatures = $true                               # wether the server should verify clients pbo signatures
    Update           = $true                               # wether to try to update Arma 3, mods and config before server start
    Headless         = $true                               # wether to start a headless client with the server
    DisableChannels  = @(0, 1, 2, 3, 4, 5)                 # radio channels to disable, see https://community.bistudio.com/wiki/enableChannel

    Admins           = @(
        76561197967609383 # Arwyn                          # steamid of players allowed to login as admin on the server
    )

    Mods             = @(                                  # list of mods used both on clients and server
        450814997                                          # workshop item id
        'C:\mods\@GSRI'                                    # absolute path to local mod
    )
    ClientMods       = @(                                  # list of mods whose keys get added to the server
        463939057
    )
    ServerMods       = @(                                  # list of mods used on the server but not by clients
        894678801
    )

    # Select one of below options, depending on how you want to obtain the mission pbo file:

    Mission          = @{                                  # the mission that will run on the server
        Type = 'Local'                                     # when you have the pbo file locally
        Path = 'C:\Arma3\instances\abcd\mission'            # the script will look into this directory
    }

    Mission          = @{                                  # the mission to run on the server
        Type = 'Github'                                    # when you want to download the pbo from GitHub
        Path = 'team-gsri/Entrainement'                    # the script will look into this repository's latest release
    }

    WorkshopPath     = 'C:\Arma3'                          # Path for workshop mods (WorkshopPath/steamapps/workshop/ ...)
    MasterPath       = 'C:\Arma3\instances\abcd\master'    # Path for the Arma3 server executable
    ConfigPath       = 'C:\Arma3\instances\abcd\config'    # Path for server.cfg, basic.cfg, and pid files
    ProfilePath      = 'C:\Arma3\instances\abcd\profile'   # Path for the server profile
}
```

CAUTION: Server and Headless affinity are bitmasks, allowing each process to run on different CPU cores for performance purpose. See https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity#system-diagnostics-process-processoraffinity[Microsoft documentation]

== Usage

The server will run under the `LocalService` account.

All commands expect a single argument with the ConfigFilename to use.
 
* `Enable-ArmaServer.ps1` and `Disable-ArmaServer.ps1` will toggle a scheduled task to restart the server on a daily basis.
** If the task does not exist, enabling it will create the task with a default schedule at 5AM ;
** Disabling a server will not actually stop the instance, unless adding the `-Stop` switch
* `Start-ArmaServer.ps1` and `Stop-ArmaServer.ps1` will start and stop the server immediately
** Starting a server will create and enable the scheduled task
** Starting a running server will restart the server, stopping the current instance first
** The script use PID files to identify the processes, so you can run multiple instances on the same box
* `Update-ArmaServer.ps1` can be used to manually update both the game, mods, configs, and mission

IMPORTANT: Due to a bug in steamcmd, download of larger mods will timeout. In that case, you can use `Start-Download.ps1`. This script will start the download and yield an error. Then you can **wait despite the error** and the download will actually continue in the background. Watch your network bandwidth for completion, then use `quit` to exit steamcmd.


