= GSRI server manager: usage guide

== Requirements

=== Softwares

* https://github.com/PowerShell/PowerShell[Pwsh 7+]: appliction runtime
* https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip[Steamcmd]: used for arma 3 server and workshop items download
* https://cli.github.com/[GitHub CLI]: used for Github repositories release content download

All 3 softwares should be accessible from the system PATH environment variable.

=== Accounts

* https://github.com/login[A github account]
* https://store.steampowered.com/login[A steam account] with the following caracteristics:
** Own https://store.steampowered.com/app/107410[Arma 3 base game] (DLC not needed)
** Not https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A[limited account] (buying Arma 3 should be enough)
** https://help.steampowered.com/en/faqs/view/06B0-26E6-2CF8-254C[Steam Guard on] is recommended

== Installation

. Login to your Steam account using the `steamcmd` command line utility
. Login to your GitHub account using the `gh` command line utility
. Set the `STEAM_USERNAME` to the steam account username used previously

== Server configuration

All configuration regarding your server must go into a configuration file. This file is expected to use PSD1 format.

Exemple file:

```psd1
@{
    Port             = 2302                                # main port used by the server
    ServerAffinity   = 5                                   # bitmask for CPU affinity of the server
    HeadlessAffinity = 10                                  # bitmask for CPU affinity of the headless client

    Hostname         = '[FR] SERVER NAME'                  # name of the server visible on the launcher
    DefaultMission   = 'CONT_Orion.Malden'                 # name of the mission the server will load at start
    Password         = 'bouh!'                             # password for client connection
    Players          = 32                                  # max players for the server
    VerifySignatures = $true                               # wether the server should verify clients pbo signatures
    Headless         = $true                               # wether to start a headless client with the server
    DisableChannels  = @(0, 1, 2, 3, 4, 5)                 # radio channels to disable, see https://community.bistudio.com/wiki/enableChannel
    Beta             = 'creatordlc'                        # optional steam beta channel
    WorkshopPath     = 'C:\Arma3'                          # Path where workshop mods get downloaded
    MasterPath       = 'C:\Arma3\instances\abcd\master'    # Path for the Arma3 server executable
    ConfigPath       = 'C:\Arma3\instances\abcd\config'    # Path for server.cfg, basic.cfg, and pid files
    ProfilePath      = 'C:\Arma3\instances\abcd\profile'   # Path for the server profile

    Admins           = @(
        76561197967609383 # Arwyn                          # steamid of players allowed to login as admin on the server
    )
    Mods             = @(                                  # list of mods used both on clients and server
        450814997                                          # - workshop item id
        'C:\mods\@GSRI'                                    # - absolute path to local mod
    )
    ClientMods       = @(                                  # list of mods whose keys get added to the server
        463939057
    )
    ServerMods       = @(                                  # list of mods used on the server but not by clients
        894678801
    )
    Missions         = @{                                  # the mission that will run on the server
        'team-gsri/Orion'                                  # - github repository
        'C:\Arma3\instances\abcd\missions'                 # - absolute path to directory with pbo missions
    }
}
```

CAUTION: Server and Headless affinity are bitmasks, allowing each process to run on different CPU cores for performance purpose. See https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity#system-diagnostics-process-processoraffinity[Microsoft documentation]

== Usage

NOTE: All commands require administrator privileges

The following commands are available:

* `Install-ArmaServer`: This command will install the server:
** Download dedicated server binaries
** Download addons from Steam workshop
** Download missions from GitHub releases
** Install BI Keys, mission files, and config files
* `Update-ArmaServer`: This command will refresh the server missions and config only
** Intended as a faster alternative when you want to test a mission / config
* `Start-ArmaServer`: Starts the server using the current user's context
** If the server is already running, it will try to stop it first
* `Stop-ArmaServer`: Stops the currently running server

IMPORTANT: Due to a bug in steamcmd, download of larger mods might timeout.
