name: release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["src/**"]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Derive semver version number based on git revision
        shell: pwsh
        run: |
          dotnet tool install -g Octopus.OctoVersion.Tool
          octoversion --CurrentBranch=${{ github.ref_name }} --OutputFormats:0=Environment >> $GITHUB_ENV

      - name: Publish module on PSGallery
        shell: pwsh
        run: build/Release.ps1 -Version ${env:OCTOVERSION_FullSemVer} -ApiKey ${{ secrets.PSGALLERY_APIKEY }} -Verbose

      - name: Tag new version on the repository
        shell: pwsh
        run: gh release create ${env:OCTOVERSION_FullSemVer} --generate-notes
